version: '3'

services:
  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres_db_nisal
    ports:
      - '5432:5555'  # Map the container port 5432 to host port 5432
    environment:
      POSTGRES_DB: "testdb_nisal"  #this is the database name
      POSTGRES_USER: "testdb_owner"
      POSTGRES_PASSWORD: "LKqhY6okCa1O"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres_data:  # Create a named volume for PostgreSQL data
